Upgrade test for Eventing Kafka channel (#877)
Cherry pick of #875

* Upgrade test for Eventing Kafka channel
* Add explicit error message
* Commiting make genertated-files on GOPATH
* Adding workaround for https://github.com/knative/eventing/issues/5176

diff --git a/.github/workflows/validate.yaml b/.github/workflows/validate.yaml
--- a/.github/workflows/validate.yaml
+++ b/.github/workflows/validate.yaml
@@ -41,7 +41,16 @@ jobs:
 
       - name: Check if everything is consistent
         working-directory: ./src/github.com/${{ github.repository }}
-        run: git diff --exit-code
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo '::debug::Running `git status`'
+            git -c color.status=always status
+            echo '::debug::Running `git diff`'
+            git -c color.ui=always diff
+            echo '::error::Not all generated files are commited. Run `make generated-files` and commit files.'
+            echo '::warning::`make generated-files` needs to be run on GOPATH due to https://github.com/knative/pkg/issues/1287'
+            exit 33
+          fi
 
   lint:
     name: Lint
