Add misspell to our presubmit linters (#981)
* Add misspell to our presubmit linters

* Fix things

diff --git a/.github/workflows/validate.yaml b/.github/workflows/validate.yaml
--- a/.github/workflows/validate.yaml
+++ b/.github/workflows/validate.yaml
@@ -81,6 +81,10 @@ jobs:
           curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b "${TEMP_PATH}" 2>&1
           echo '::endgroup::'
 
+          echo '::group:: Installing misspell ... https://github.com/client9/misspell'
+          go get github.com/client9/misspell/cmd/misspell
+          echo '::endgroup::'
+
           echo '::group:: Installing woke ... https://github.com/get-woke/woke'
           curl -sfL https://raw.githubusercontent.com/get-woke/woke/main/install.sh | sh -s -- -b "${TEMP_PATH}" "${WOKE_VERSION}" 2>&1
           echo '::endgroup::'
@@ -132,3 +136,18 @@ jobs:
         working-directory: ./src/github.com/${{ github.repository }}
         run: |
           operator-sdk bundle validate ./olm-catalog/serverless-operator
+
+      - name: Spelling
+        working-directory: ./src/github.com/${{ github.repository }}
+        env:
+          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
+        run: |
+          # Don't fail because of misspell
+          set +o pipefail
+          git ls-files | grep -Ev '^(vendor/|.git)' | xargs misspell -error xargs misspell -error \
+            | reviewdog -efm="%f:%l:%c: %m" \
+                -name="github.com/client9/misspell" \
+                -reporter="github-pr-check" \
+                -filter-mode="added" \
+                -fail-on-error="true" \
+                -level="error"
